### ISSUE TITLE
Cannot read property 'getArgs' of undefined

### ISSUE THREAD

**Issue by tomatobrown** [gkushang/cucumber-parallel#11]
When using cucumber ^2.0.0-rc.6

Exception Thrown

> TypeError: Cannot read property 'getArgs' of undefined
>     at getConfiguration (/Users/tmader-brown/gitlab/implementations-cucumber/cucumberjs/node_modules/cucumber-parallel/lib/cucumber/cucumber_js.js:71:58)
>     at Object.runCucumber (/Users/tmader-brown/gitlab/implementations-cucumber/cucumberjs/node_modules/cucumber-parallel/lib/cucumber/cucumber_js.js:86:29)
>     at Object.<anonymous> (/Users/tmader-brown/gitlab/implementations-cucumber/cucumberjs/node_modules/cucumber-parallel/lib/parallelizer/runner.js:4:26)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.runMain (module.js:605:10)
>     at run (bootstrap_node.js:418:7)
>     at startup (bootstrap_node.js:139:9)
>     at bootstrap_node.js:533:3
> /Users/tmader-brown/gitlab/implementations-cucumber/cucumberjs/node_modules/cucumber-parallel/lib/cucumber/cucumber_js.js:71
>             var profileArgs = Cucumber.Cli.ProfilesLoader.getArgs(program.profile);

**Comment by funkyvisions** [comment]
Any plans to fix this and work with Cucumber.js 2.x?

**Comment by gkushang** [comment]
Definitely. I have tagged the issue as an `enhancement` and `help wanted`. 

Thanks for reporting!

**Comment by gkushang** [comment]
https://github.com/gkushang/cucumber-parallel/pull/15 would resolve this issue. It will add a support for Cucumber 2

**Comment by gkushang** [comment]
@tomatobrown @funkyvisions 

resolved & published V2 - https://www.npmjs.com/package/cucumber-parallel . Please try and let me know if you face any issues.

Thanks!
